### ISSUE TITLE
[Feature Request] Count grouped messages as one

### ISSUE THREAD

**Issue by PiRomant** [Catogram/Catogram#112] opened 2021-05-09 11:28 UTC
The large number on the message counter is misleading, when in fact there is only one post.

**Comment by rfoxxxy** [comment] 2021-05-09 11:36
@PiRomant telegram interpreting grouped media messages as stack of ordinary messages
and you should go to bugs.telegram.org with this issue)

**Comment by PiRomant** [comment] 2021-05-09 11:43
The author decides whether to group the images/files or not. Grouping occurs when publishing using the "Group" checkbox.

**Comment by iTaysonLab** [comment] 2021-07-25 16:16
Sorry to answer after 3 months - but "Group items" checkbox just assigns a special "media album ID" to messages. Telegram API (and so official client/CG/any other) still see this "album" as a bunch of messages.

But personally I don't know if this is intended behavior or it is a real bug. You should really go to Telegram's bug platform (if you haven't done that yet, of course).

Closing this issue because it is a Telegram behavior, not Catogram-specific.

**Closed by iTaysonLab** 2021-07-25 16:16 UTC

**Comment by PiRomant** [comment] 2021-07-25 16:29
How about option: don't count messages with "media album ID"
